// Build step for @finplan/contracts (run by `npm run build` and `npm pack`).
//
// Single source of version truth: contracts/VERSION. This script
//  1. writes the version into package.json and src/version.ts;
//  2. copies the language-neutral contract data (schemas, domain registry, fixtures,
//     conformance cases, ownership matrix) into ./data, so the npm artifact ships
//     the same content as the Python wheel (consumer-mode conformance reads it);
//  3. embeds every schema of contracts/core and contracts/<domain> plus the domain
//     registry into src/bundle.ts, so validation needs no file system at runtime.
// Logs go to stderr: `npm pack --json` output on stdout is parsed by the digest step.
import { cpSync, existsSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkgDir = join(here, "..");
const contracts = join(pkgDir, "..");
const version = readFileSync(join(contracts, "VERSION"), "utf8").trim();
if (!/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/.test(version)) {
  throw new Error(`contracts/VERSION is not a semantic version: ${version}`);
}

// 1. version
const pkgPath = join(pkgDir, "package.json");
const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
if (pkg.version !== version) {
  pkg.version = version;
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
}
writeFileSync(
  join(pkgDir, "src", "version.ts"),
  `// Generated by scripts/sync.mjs from contracts/VERSION - do not edit.\nexport const VERSION = ${JSON.stringify(version)};\n`,
);

// 2. data copy
const data = join(pkgDir, "data");
rmSync(data, { recursive: true, force: true });
for (const part of ["VERSION", "core", "finance", "domains", "fixtures", "conformance", "ownership"]) {
  const src = join(contracts, part);
  if (existsSync(src)) cpSync(src, join(data, part), { recursive: true });
}

// 3. embedded schema bundle (same discovery rules as finplan_contracts.schemas)
const ID_BASE = "https://contracts.finplan.invalid/";
const NON_SCHEMA_DIRS = new Set(["fixtures", "domains", "ownership", "conformance", "python", "typescript", "templates", "node_modules"]);
const walkJson = (dir) =>
  readdirSync(dir)
    .sort()
    .flatMap((name) => {
      const p = join(dir, name);
      return statSync(p).isDirectory() ? walkJson(p) : name.endsWith(".json") ? [p] : [];
    });
const schemas = [];
for (const ns of readdirSync(contracts).sort()) {
  const nsDir = join(contracts, ns);
  if (NON_SCHEMA_DIRS.has(ns) || ns.startsWith(".") || !statSync(nsDir).isDirectory()) continue;
  for (const major of readdirSync(nsDir).sort()) {
    const majorDir = join(nsDir, major);
    if (!/^v[0-9]+$/.test(major) || !statSync(majorDir).isDirectory()) continue;
    for (const file of walkJson(majorDir)) {
      const name = relative(majorDir, file).split(sep).join("/").replace(/\.json$/, "");
      const schema = JSON.parse(readFileSync(file, "utf8"));
      const id = `${ID_BASE}${ns}/v${Number(major.slice(1))}/${name}.json`;
      if (schema.$id !== id) throw new Error(`${file}: $id ${JSON.stringify(schema.$id)} does not match its location (expected ${JSON.stringify(id)})`);
      if (schemas.some((s) => s.name === name)) throw new Error(`duplicate schema name ${JSON.stringify(name)}`);
      schemas.push({ name, namespace: ns, major: Number(major.slice(1)), id, schema });
    }
  }
}
schemas.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
const domainRegistry = JSON.parse(readFileSync(join(contracts, "domains", "registry.json"), "utf8"));
const bundle = { version, schemas, domainRegistry };
writeFileSync(
  join(pkgDir, "src", "bundle.ts"),
  "// Generated by scripts/sync.mjs from contracts/{core,<domain>,domains} - do not edit.\n" +
    'import type { ContractBundle } from "./schemas.js";\n' +
    `export const BUNDLE: ContractBundle = JSON.parse(${JSON.stringify(JSON.stringify(bundle))});\n`,
);
console.error(`@finplan/contracts synced to ${version}: ${schemas.length} schemas embedded`);
