"""Environment isolation guardrails for the single account (design D5; tasks 9.1, 9.3, 12.3).

Permission boundaries
---------------------
Every role a pipeline creates carries one permission boundary (a role has at most
one), named ``finplan-<env>-permission-boundary`` or, for FinanceModel research
and job-execution roles, ``finplan-<env>-research-permission-boundary``. Account-level
tooling roles (environment ``shared``) carry ``finplan-shared-permission-boundary``.

Each boundary allows everything except (statements in order):

* ``DenyOtherEnvironmentTagged`` (env boundaries): any action on a resource whose
  ``environment`` tag is another environment (``shared``-tagged resources stay
  reachable: they hold no environment data) - ENV-03, ENV-18;
* ``DenyOtherEnvironmentNamed`` (env boundaries): any action on a resource named
  under another environment's prefix (``finplan-<other-env>-*`` resource names,
  ``/finplan/<other-env>/*`` SSM paths and ``finplan/<other-env>/*`` secret names) - ENV-03,
  ENV-18. The resources are written as one ARN pattern per service
  (:data:`NAMED_RESOURCE_ARNS`) with the ``${AWS::Partition}``, ``${AWS::Region}`` and
  ``${AWS::AccountId}`` pseudo parameters, so IAM and cfn-lint (E3510) accept them; a service
  wildcard such as ``arn:*:*:*:*:*finplan-<env>-*`` is not a valid IAM resource ARN. The
  tag-based statement above stays the primary control for services whose ARNs carry no name;
* ``DenyLiveFinancialActions`` / ``DenyLiveFinancialSecrets``: the live-financial
  deny list (payments, wallets, blockchain/exchange actions and any secret whose
  name refers to brokerage, trading, exchange, wallet or payment credentials) -
  ENV-05;
* ``ProtectBoundaries``: removing or swapping permission boundaries, and creating
  roles without the environment boundary;
* ``ProtectBudgetEnforcement``: detaching the budget deny policy or executing a
  budget action (only a human may remove the deny, ENV-19);
* research boundaries only (ENV-04): ``DenyPlatformMetadataTables`` (all DynamoDB
  access to FinancialPlanning tables), ``DenyPlanApiWrites`` (write methods on
  the plan API paths: plans, plan versions, publications, executions, portfolios,
  staged-output accept) and ``DenyWritesOutsideResearchAndStaging`` (S3 writes
  anywhere except FinanceModel research storage and the run-output staging area).

Every boundary function takes ``partition``, ``region`` and ``account`` (default: the
CloudFormation pseudo parameters). With the defaults the document is CloudFormation-ready: every
string containing ``${AWS::...}`` is wrapped in ``Fn::Sub`` (:func:`finplan_contracts.iam.to_cfn`).
With concrete values (offline policy simulation: ``partition="aws"``, ``region="us-east-2"``,
``account="<account-id>"``) the strings are plain. :func:`concrete_boundary` does the same for an
already generated document.

Resource naming convention assumed by the name-based statements:
``finplan-<env>-<repo>-<logical-role>[-<suffix>]`` (``<env>`` is ``beta|gamma|prod``
or ``shared``), SSM parameters ``/finplan/<env>/<repo>/<category>/<name>``.

Static template checks
----------------------
* :func:`check_role_boundaries` (ENV-18): every ``AWS::IAM::Role`` in a
  synthesized template has the permission boundary of its environment; failures
  name the role. Boundary references are rendered from ``Ref`` (to a managed policy or a
  parameter default), ``Fn::Sub``, ``Fn::Join`` and ``Fn::ImportValue``; pseudo-parameter
  ``Ref``s (``AWS::Partition``, ``AWS::AccountId``, ``AWS::Region`` ...) render as
  placeholders, so the ``Fn::Join`` CDK writes for a boundary ARN is resolved.
* :func:`check_shared_resources` (ENV-16): a resource tagged ``environment``
  ``shared`` must belong to an ownership-matrix row with ``scope: shared`` and
  ``environment_data: false``; resources holding environment data (snapshots,
  plans, run outputs) tagged ``shared`` fail, and resources whose matrix row says
  ``iac_declared: false`` (the pre-existing Jev API key secret) fail when declared.

CDK wiring of these templates happens in the add-platform-foundation change; the
JSON fragments under ``contracts/templates/`` are generated by :func:`generate_templates`.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping

import yaml

from .schemas import contracts_root

__all__ = [
    "ENVIRONMENTS",
    "SHARED",
    "LIVE_FINANCIAL_DENY_ACTIONS",
    "LIVE_FINANCIAL_SECRET_PATTERNS",
    "BUDGET_DENY_POLICY_NAME",
    "boundary_name",
    "research_boundary_name",
    "resource_name",
    "env_permission_boundary",
    "research_permission_boundary",
    "shared_permission_boundary",
    "concrete_boundary",
    "named_resource_arns",
    "NAMED_RESOURCE_ARNS",
    "MANAGED_POLICY_MAX_CHARS",
    "policy_size",
    "PSEUDO_PLACEHOLDERS",
    "live_financial_deny_statements",
    "Finding",
    "check_role_boundaries",
    "check_shared_resources",
    "load_matrix",
    "generate_templates",
]

ENVIRONMENTS = ("beta", "gamma", "prod")
SHARED = "shared"
BOUNDARY_TEMPLATE = "finplan-{env}-permission-boundary"
RESEARCH_BOUNDARY_TEMPLATE = "finplan-{env}-research-permission-boundary"
BUDGET_DENY_POLICY_NAME = "finplan-budget-enforcement-deny"

#: Live trading, brokerage/exchange, payments and wallet actions (ENV-05).
LIVE_FINANCIAL_DENY_ACTIONS: list[str] = [
    "payments:*",
    "payment:*",
    "payment-cryptography:*",
    "payment-cryptography-data:*",
    "managedblockchain:*",
    "managedblockchain-query:*",
    "wallet:*",
    "wallets:*",
    "coinbase:*",
    "brokerage:*",
    "trading:*",
    "exchange:*",
    "crypto-exchange:*",
    "bedrock-agentcore:*Payment*",
    "bedrock-agentcore:*Wallet*",
    "bedrock-agentcore:*Funds*",
    # 0.2.1: the former ``bedrock-agentcore-control:*`` entries were removed. The AWS Service
    # Authorization Reference documents one IAM prefix for Amazon Bedrock AgentCore,
    # ``bedrock-agentcore``, covering both its control-plane and data-plane APIs; the
    # ``bedrock-agentcore-control`` name is the SDK client name, not an IAM service prefix, so those
    # entries matched no action. The ``bedrock-agentcore:`` entries above already cover them.
]
#: Secret names that would hold live-financial credentials (brokerage, trading, exchanges such as Coinbase, wallets, payments).
LIVE_FINANCIAL_SECRET_PATTERNS: list[str] = [
    "*brokerage*", "*broker*", "*trading*", "*trade-*", "*coinbase*", "*binance*", "*kraken*", "*alpaca*", "*ibkr*", "*robinhood*",
    "*exchange-api*", "*crypto-exchange*", "*wallet*", "*payment*",
]
LIVE_FINANCIAL_SECRET_ACTIONS: list[str] = [
    "secretsmanager:GetSecretValue",
    "secretsmanager:PutSecretValue",
    "secretsmanager:UpdateSecret",
    "secretsmanager:BatchGetSecretValue",
]

#: Logical roles of FinancialPlanning metadata tables (ownership matrix row platform-metadata-tables).
PLAN_API_WRITE_METHODS = ("POST", "PUT", "PATCH", "DELETE")
PLAN_API_WRITE_PATHS = ("v1/plans", "v1/plans/*", "v1/portfolios", "v1/portfolios/*", "v1/publications", "v1/publications/*", "v1/executions", "v1/executions/*")
#: The same write routes as compact execute-api patterns: ``P*`` is POST, PUT and PATCH (no other
#: HTTP method starts with P) and ``v1/plans*`` covers ``v1/plans`` and ``v1/plans/*`` (including
#: the staged-output accept route); no other route starts with these prefixes.
PLAN_API_WRITE_METHOD_PATTERNS = ("P*", "DELETE")
PLAN_API_WRITE_PATH_PATTERNS = ("v1/plans*", "v1/portfolios*", "v1/publications*", "v1/executions*")
S3_WRITE_ACTIONS = [
    "s3:PutObject",
    "s3:PutObjectAcl",
    "s3:PutObjectTagging",
    "s3:PutObjectRetention",
    "s3:PutObjectLegalHold",
    "s3:DeleteObject",
    "s3:DeleteObjectVersion",
    "s3:DeleteObjectTagging",
    "s3:RestoreObject",
    "s3:PutBucket*",
    "s3:DeleteBucket*",
]


def boundary_name(env: str) -> str:
    if env not in ENVIRONMENTS + (SHARED,):
        raise ValueError(f"unknown environment {env!r}")
    return BOUNDARY_TEMPLATE.format(env=env)


def research_boundary_name(env: str) -> str:
    if env not in ENVIRONMENTS:
        raise ValueError(f"unknown environment {env!r}")
    return RESEARCH_BOUNDARY_TEMPLATE.format(env=env)


def resource_name(env: str, repo: str, logical_role: str, suffix: str | None = None) -> str:
    """Resource name per the naming convention ``finplan-<env>-<repo>-<logical-role>[-<suffix>]``."""
    if env not in ENVIRONMENTS + (SHARED,):
        raise ValueError(f"unknown environment {env!r}")
    name = f"finplan-{env}-{repo}-{logical_role}"
    return f"{name}-{suffix}" if suffix else name


def _boundary_arn_pattern(name: str) -> str:
    return f"arn:*:iam::*:policy/{name}"


PARTITION = "${AWS::Partition}"
REGION = "${AWS::Region}"
ACCOUNT = "${AWS::AccountId}"

#: Per-service ARN patterns of resources named under an environment (``{p}`` partition, ``{r}``
#: region, ``{a}`` account, ``{e}`` environment). Names follow ``finplan-<env>-<repo>-<role>[-...]``,
#: SSM parameters ``/finplan/<env>/...`` (``/finplan/<env>*`` also covers the bare path; no
#: environment name is a prefix of another) and secrets ``finplan/<env>/...``. The list covers the
#: services the four repositories name resources in; it is kept short because a boundary must fit
#: IAM's managed-policy size limit (:data:`MANAGED_POLICY_MAX_CHARS`). Every other service is covered
#: by ``DenyOtherEnvironmentTagged``.
NAMED_RESOURCE_ARNS: tuple[str, ...] = (
    "arn:{p}:s3:::finplan-{e}-*",
    "arn:{p}:dynamodb:{r}:{a}:table/finplan-{e}-*",
    "arn:{p}:lambda:{r}:{a}:function:finplan-{e}-*",
    "arn:{p}:iam::{a}:role/finplan-{e}-*",
    "arn:{p}:iam::{a}:policy/finplan-{e}-*",
    "arn:{p}:ssm:{r}:{a}:parameter/finplan/{e}*",
    "arn:{p}:secretsmanager:{r}:{a}:secret:finplan/{e}/*",
    "arn:{p}:sqs:{r}:{a}:finplan-{e}-*",
    "arn:{p}:sns:{r}:{a}:finplan-{e}-*",
    "arn:{p}:logs:{r}:{a}:log-group:*finplan-{e}-*",
    "arn:{p}:events:{r}:{a}:rule/finplan-{e}-*",
    "arn:{p}:scheduler:{r}:{a}:schedule/*/finplan-{e}-*",
    "arn:{p}:states:{r}:{a}:*:finplan-{e}-*",
    "arn:{p}:cloudformation:{r}:{a}:stack/finplan-{e}-*",
    "arn:{p}:sagemaker:{r}:{a}:*/finplan-{e}-*",
)
#: IAM's size limit for a managed policy (characters, whitespace excluded); every generated
#: boundary must stay below it once the pseudo parameters are resolved.
MANAGED_POLICY_MAX_CHARS = 6144


def policy_size(doc: Any, *, partition: str = "aws", region: str = "us-east-2", account: str = "x" * 12) -> int:
    """Characters IAM counts for ``doc`` (whitespace excluded) once its pseudo parameters are resolved
    (the account defaults to a 12-character stand-in, the length of a real account ID)."""
    return len(re.sub(r"\s", "", json.dumps(concrete_boundary(doc, partition=partition, region=region, account=account), separators=(",", ":"))))


def named_resource_arns(env: str, *, partition: str = PARTITION, region: str = REGION, account: str = ACCOUNT) -> list[str]:
    """ARN patterns of every resource named under ``env`` (one per service, :data:`NAMED_RESOURCE_ARNS`)."""
    if env not in ENVIRONMENTS:
        raise ValueError(f"unknown environment {env!r}")
    return [t.format(p=partition, r=region, a=account, e=env) for t in NAMED_RESOURCE_ARNS]


def _finish(doc: dict[str, Any], partition: str, region: str, account: str) -> dict[str, Any]:
    """CloudFormation-ready (``Fn::Sub``) with pseudo parameters, plain strings with concrete values."""
    from .iam import to_cfn

    return to_cfn(doc) if any("${AWS::" in v for v in (partition, region, account)) else doc


def concrete_boundary(doc: Any, *, partition: str = "aws", region: str = "us-east-2", account: str = "<account-id>") -> Any:
    """A generated boundary with its pseudo parameters substituted (``Fn::Sub`` unwrapped), for offline simulation."""
    from .iam import substitute

    return substitute(doc, {"AWS::Partition": partition, "AWS::Region": region, "AWS::AccountId": account})


# ===================================================================== statements
def live_financial_deny_statements() -> list[dict[str, Any]]:
    """Live-financial deny list (ENV-05).

    Secrets are matched by the request's secret identifier and the new secret's name
    (condition keys ``secretsmanager:SecretId`` / ``secretsmanager:Name``), so the
    boundary itself contains no live-financial secret reference.
    """
    return [
        {"Sid": "DenyLiveFinancialActions", "Effect": "Deny", "Action": list(LIVE_FINANCIAL_DENY_ACTIONS), "Resource": "*"},
        {
            "Sid": "DenyLiveFinancialSecrets",
            "Effect": "Deny",
            "Action": list(LIVE_FINANCIAL_SECRET_ACTIONS),
            "Resource": "*",
            "Condition": {"StringLike": {"secretsmanager:SecretId": list(LIVE_FINANCIAL_SECRET_PATTERNS)}},
        },
        {
            "Sid": "DenyLiveFinancialSecretCreation",
            "Effect": "Deny",
            "Action": ["secretsmanager:CreateSecret"],
            "Resource": "*",
            "Condition": {"StringLike": {"secretsmanager:Name": list(LIVE_FINANCIAL_SECRET_PATTERNS)}},
        },
    ]


def _protect_statements(allowed_boundaries: list[str]) -> list[dict[str, Any]]:
    return [
        {
            "Sid": "ProtectBoundaries",
            "Effect": "Deny",
            "Action": ["iam:DeleteRolePermissionsBoundary", "iam:DeleteUserPermissionsBoundary"],
            "Resource": "*",
        },
        {
            "Sid": "RequireBoundaryOnRoleCreation",
            "Effect": "Deny",
            "Action": ["iam:CreateRole", "iam:PutRolePermissionsBoundary", "iam:CreateUser", "iam:PutUserPermissionsBoundary"],
            "Resource": "*",
            "Condition": {"ArnNotLike": {"iam:PermissionsBoundary": [_boundary_arn_pattern(n) for n in allowed_boundaries]}},
        },
        {
            "Sid": "ProtectBoundaryPolicies",
            "Effect": "Deny",
            "Action": ["iam:CreatePolicyVersion", "iam:DeletePolicy", "iam:DeletePolicyVersion", "iam:SetDefaultPolicyVersion"],
            "Resource": [_boundary_arn_pattern("finplan-*-permission-boundary")],
        },
        {
            "Sid": "ProtectBudgetEnforcement",
            "Effect": "Deny",
            "Action": ["iam:DetachRolePolicy", "iam:DetachUserPolicy", "iam:DetachGroupPolicy"],
            "Resource": "*",
            "Condition": {"ArnLike": {"iam:PolicyARN": _boundary_arn_pattern(BUDGET_DENY_POLICY_NAME)}},
        },
        {"Sid": "OnlyHumansExecuteBudgetActions", "Effect": "Deny", "Action": ["budgets:ExecuteBudgetAction"], "Resource": "*"},
    ]


def _cross_env_statements(env: str, partition: str = PARTITION, region: str = REGION, account: str = ACCOUNT) -> list[dict[str, Any]]:
    others = [e for e in ENVIRONMENTS if e != env]
    named: list[str] = []
    for o in others:
        named += named_resource_arns(o, partition=partition, region=region, account=account)
    return [
        {
            "Sid": "DenyOtherEnvironmentTagged",
            "Effect": "Deny",
            "Action": "*",
            "Resource": "*",
            "Condition": {
                "StringNotEquals": {"aws:ResourceTag/environment": [env, SHARED]},
                "Null": {"aws:ResourceTag/environment": "false"},
            },
        },
        {"Sid": "DenyOtherEnvironmentNamed", "Effect": "Deny", "Action": "*", "Resource": named},
    ]


def _allow_all() -> dict[str, Any]:
    return {"Sid": "AllowWithinBoundary", "Effect": "Allow", "Action": "*", "Resource": "*"}


def _env_boundary_doc(env: str, partition: str, region: str, account: str) -> dict[str, Any]:
    if env not in ENVIRONMENTS:
        raise ValueError(f"unknown environment {env!r}")
    return {
        "Version": "2012-10-17",
        "Statement": [_allow_all(), *_cross_env_statements(env, partition, region, account), *live_financial_deny_statements(), *_protect_statements([boundary_name(env), research_boundary_name(env)])],
    }


def env_permission_boundary(env: str, *, partition: str = PARTITION, region: str = REGION, account: str = ACCOUNT) -> dict[str, Any]:
    """Boundary for every pipeline-created role of ``env`` (ENV-03, ENV-05, ENV-18).

    CloudFormation-ready (``Fn::Sub``) by default; pass concrete ``partition``/``region``/``account``
    for offline policy simulation (module docstring).
    """
    return _finish(_env_boundary_doc(env, partition, region, account), partition, region, account)


def research_permission_boundary(env: str, *, partition: str = PARTITION, region: str = REGION, account: str = ACCOUNT) -> dict[str, Any]:
    """Boundary for FinanceModel research and job-execution roles of ``env`` (ENV-04)."""
    base = _env_boundary_doc(env, partition, region, account)
    api_writes = [f"arn:{partition}:execute-api:{region}:{account}:*/*/{m}/{p}" for m in PLAN_API_WRITE_METHOD_PATTERNS for p in PLAN_API_WRITE_PATH_PATTERNS]
    research = [
        {
            "Sid": "DenyPlatformMetadataTables",
            "Effect": "Deny",
            "Action": "dynamodb:*",
            "Resource": [f"arn:{partition}:dynamodb:{region}:{account}:table/finplan-*-financialplanning-*"],
        },
        {
            "Sid": "DenyPlatformMetadataTablesTagged",
            "Effect": "Deny",
            "Action": "dynamodb:*",
            "Resource": "*",
            "Condition": {"StringEquals": {"aws:ResourceTag/owner-repo": "financialplanning"}},
        },
        {"Sid": "DenyPlanApiWrites", "Effect": "Deny", "Action": "execute-api:Invoke", "Resource": api_writes},
        {
            "Sid": "DenyWritesOutsideResearchAndStaging",
            "Effect": "Deny",
            "Action": list(S3_WRITE_ACTIONS),
            "NotResource": [
                f"arn:{partition}:s3:::finplan-{env}-financemodel-*",
                f"arn:{partition}:s3:::finplan-{env}-financialplanning-run-staging-area*",
            ],
        },
    ]
    base["Statement"] = base["Statement"][:3] + research + base["Statement"][3:]
    return _finish(base, partition, region, account)


def shared_permission_boundary() -> dict[str, Any]:
    """Boundary for account-level tooling roles (pipeline, budget action execution).

    It carries the live-financial deny and the boundary/budget protections; it has
    no environment deny because tooling roles orchestrate all three environments
    (per-environment deploy roles carry the environment boundaries).
    """
    allowed = [boundary_name(SHARED)] + [boundary_name(e) for e in ENVIRONMENTS] + [research_boundary_name(e) for e in ENVIRONMENTS]
    return {"Version": "2012-10-17", "Statement": [_allow_all(), *live_financial_deny_statements(), *_protect_statements(allowed)]}


# ===================================================================== template checks
@dataclass(frozen=True)
class Finding:
    check: str
    resource: str
    message: str

    def __str__(self) -> str:
        return f"[{self.check}] {self.resource}: {self.message}"


def _tags(props: Mapping[str, Any]) -> dict[str, Any]:
    tags = props.get("Tags") or props.get("ResourceTags") or []
    if isinstance(tags, dict):
        return dict(tags)
    out = {}
    for t in tags if isinstance(tags, list) else []:
        if isinstance(t, dict) and "Key" in t:
            out[t["Key"]] = t.get("Value")
    return out


#: Placeholders used when rendering pseudo-parameter references (never real values).
PSEUDO_PLACEHOLDERS: dict[str, str] = {
    "AWS::Partition": "aws",
    "AWS::AccountId": "<account-id>",
    "AWS::Region": "<region>",
    "AWS::URLSuffix": "amazonaws.com",
    "AWS::StackName": "<stack-name>",
    "AWS::StackId": "<stack-id>",
}


def _render(value: Any, template: Mapping[str, Any]) -> str | None:
    """Best-effort rendering of a CloudFormation value to a string (for name checks).

    Pseudo-parameter references (``{"Ref": "AWS::Partition"}`` and friends, also as
    ``${AWS::...}`` inside ``Fn::Sub``) render as :data:`PSEUDO_PLACEHOLDERS`.
    """
    resources = template.get("Resources", {}) or {}
    params = template.get("Parameters", {}) or {}
    if isinstance(value, str):
        return value
    if isinstance(value, dict) and len(value) == 1:
        (fn, arg), = value.items()
        if fn == "Ref" and isinstance(arg, str):
            if arg in PSEUDO_PLACEHOLDERS:
                return PSEUDO_PLACEHOLDERS[arg]
            res = resources.get(arg)
            if isinstance(res, dict) and res.get("Type") == "AWS::IAM::ManagedPolicy":
                name = (res.get("Properties") or {}).get("ManagedPolicyName")
                rn = _render(name, template) if name is not None else None
                return f"arn:aws:iam::<account-id>:policy/{rn}" if rn else None
            if arg in params:
                d = params[arg].get("Default")
                return d if isinstance(d, str) else None
            return None
        if fn == "Fn::Sub":
            s = arg[0] if isinstance(arg, list) else arg
            if not isinstance(s, str):
                return None
            mapping = arg[1] if isinstance(arg, list) and len(arg) > 1 and isinstance(arg[1], dict) else {}

            def rep(m: re.Match[str]) -> str:
                k = m.group(1)
                if k in mapping:
                    return _render(mapping[k], template) or "*"
                if k in params and isinstance(params[k].get("Default"), str):
                    return params[k]["Default"]
                if k in PSEUDO_PLACEHOLDERS:
                    return PSEUDO_PLACEHOLDERS[k]
                return "*"

            return re.sub(r"\$\{([^}!]+)\}", rep, s)
        if fn == "Fn::Join" and isinstance(arg, list) and len(arg) == 2:
            parts = [_render(p, template) for p in arg[1]] if isinstance(arg[1], list) else None
            if parts is None or any(p is None for p in parts):
                return None
            return str(arg[0]).join(parts)  # type: ignore[arg-type]
        if fn == "Fn::ImportValue":
            return _render(arg, template)
    return None


def _role_environment(props: Mapping[str, Any], template: Mapping[str, Any], default_env: str | None) -> str | None:
    env = _tags(props).get("environment")
    if isinstance(env, str):
        return env
    if env is not None:
        rendered = _render(env, template)
        if rendered in ENVIRONMENTS + (SHARED,):
            return rendered
    return default_env


def check_role_boundaries(template: Mapping[str, Any], environment: str | None = None) -> list[Finding]:
    """ENV-18: every IAM role has the permission boundary of its environment.

    The role's environment is its ``environment`` tag, else ``environment``.
    Research roles (``logical-role`` tag containing ``research`` or ``job``, or
    owner FinanceModel with the research boundary) may use the research boundary.
    """
    findings = []
    for lid, res in sorted((template.get("Resources") or {}).items()):
        if not isinstance(res, dict) or res.get("Type") != "AWS::IAM::Role":
            continue
        props = res.get("Properties") or {}
        env = _role_environment(props, template, environment)
        pb = props.get("PermissionsBoundary")
        if pb is None:
            findings.append(Finding("permission-boundary", lid, "IAM role has no environment permission boundary"))
            continue
        if env not in ENVIRONMENTS + (SHARED,):
            findings.append(Finding("permission-boundary", lid, "IAM role has no environment tag, so its boundary cannot be verified"))
            continue
        rendered = _render(pb, template)
        allowed = {boundary_name(env)} | ({research_boundary_name(env)} if env in ENVIRONMENTS else set())
        if not rendered or not any(re.search(rf"(^|[:/]){re.escape(n)}$", rendered) for n in allowed):
            findings.append(Finding("permission-boundary", lid, f"IAM role (environment {env}) must use the permission boundary {' or '.join(sorted(allowed))}, got {rendered or 'an unresolvable value'}"))
    return findings


# ----------------------------------------------------------------- ENV-16
def load_matrix(root: str | Path | None = None) -> dict[str, Any]:
    path = contracts_root(root) / "ownership" / "matrix.yaml"
    return yaml.safe_load(path.read_text(encoding="utf-8"))


#: Resource types that hold data; an environment-data row placed under `shared` fails.
DATA_RESOURCE_TYPES = {"AWS::S3::Bucket", "AWS::DynamoDB::Table", "AWS::DynamoDB::GlobalTable", "AWS::RDS::DBInstance", "AWS::RDS::DBCluster", "AWS::EFS::FileSystem", "AWS::SecretsManager::Secret", "AWS::SSM::Parameter", "AWS::SQS::Queue", "AWS::Kinesis::Stream"}


def _rows_by_logical_role(matrix: Mapping[str, Any]) -> dict[str, list[dict[str, Any]]]:
    out: dict[str, list[dict[str, Any]]] = {}
    for row in matrix.get("resources", []):
        for lr in row.get("logical_roles") or []:
            out.setdefault(lr, []).append(row)
    return out


def _non_declarable_rows(matrix: Mapping[str, Any]) -> list[dict[str, Any]]:
    return [r for r in matrix.get("resources", []) if r.get("iac_declared") is False]


def _secret_names_of(row: Mapping[str, Any]) -> list[str]:
    refs = row.get("reference")
    refs = refs if isinstance(refs, list) else [refs]
    names = []
    for r in refs:
        if isinstance(r, str) and r.startswith("secret name "):
            names.append(r[len("secret name ") :].strip())
    return names


def check_shared_resources(template: Mapping[str, Any], matrix: Mapping[str, Any] | None = None, repo: str | None = None) -> list[Finding]:
    """ENV-16: no environment data in ``shared`` resources; pre-existing secrets are never declared."""
    matrix = matrix if matrix is not None else load_matrix()
    by_role = _rows_by_logical_role(matrix)
    shared_rows = set((matrix.get("shared_rows") or {}).keys())
    findings: list[Finding] = []
    for lid, res in sorted((template.get("Resources") or {}).items()):
        if not isinstance(res, dict):
            continue
        rtype = res.get("Type", "")
        props = res.get("Properties") or {}
        tags = _tags(props)
        env = tags.get("environment")
        lrole = tags.get("logical-role")
        owner = tags.get("owner-repo") or repo
        # pre-existing / external resources that no repository may declare
        for row in _non_declarable_rows(matrix):
            types = set(row.get("resource_types") or [])
            if rtype not in types:
                continue
            names = _secret_names_of(row)
            declared_name = _render(props.get("Name"), template) if props.get("Name") is not None else None
            if (declared_name and declared_name in names) or (lrole and lrole in (row.get("logical_roles") or [])) or (not names and rtype in types):
                findings.append(Finding("iac-not-declared", lid, f"{row['id']} is {'pre-existing' if row.get('pre_existing') else 'external'} and must not be declared in any IaC"))
        if env != SHARED:
            continue
        rows = [r for r in by_role.get(lrole, []) if (owner is None or r.get("owner") == owner)] if lrole else []
        if not rows:
            findings.append(Finding("shared-resource", lid, f"resource tagged environment=shared has no shared ownership-matrix row (logical-role {lrole!r})"))
            continue
        # A repository may own a shared and an environment row for the same logical role (its pipeline
        # row and its per-environment pipeline-role row); the shared tag selects the shared one.
        shared_scoped = [r for r in rows if r.get("scope") == SHARED]
        if shared_scoped:
            rows = shared_scoped
        for row in rows:
            if row.get("scope") != SHARED or row["id"] not in shared_rows:
                findings.append(Finding("shared-environment-data", lid, f"{row['id']} holds per-environment data (scope {row.get('scope')}) and cannot be tagged environment=shared"))
            elif row.get("environment_data") is not False:
                findings.append(Finding("shared-environment-data", lid, f"{row['id']} is shared but does not declare environment_data: false"))
        # environment data inside a shared resource: env-scoped names/prefixes in its properties
        if rtype in DATA_RESOURCE_TYPES:
            blob = json.dumps(props)
            for e in ENVIRONMENTS:
                if re.search(rf"(finplan-{e}-|/finplan/{e}/|\b{e}/(snapshots|plans|run-outputs|staging)\b)", blob):
                    findings.append(Finding("shared-environment-data", lid, f"shared resource references {e} environment data"))
                    break
    return findings


# ===================================================================== templates
def _managed_policy_template(logical_id: str, name: str, description: str, document: dict[str, Any], env: str) -> dict[str, Any]:
    return {
        "AWSTemplateFormatVersion": "2010-09-09",
        "Description": description,
        "Resources": {
            logical_id: {
                "Type": "AWS::IAM::ManagedPolicy",
                "Properties": {"ManagedPolicyName": name, "Description": description[:1000], "PolicyDocument": document},
            }
        },
        "Outputs": {logical_id + "Arn": {"Value": {"Ref": logical_id}}},
        "Metadata": {"finplan": {"generated_by": "finplan_contracts.boundaries", "environment": env, "cdk_wiring": "add-platform-foundation"}},
    }


def generate_templates() -> dict[str, dict[str, Any]]:
    """All guardrail templates, keyed by file name under ``contracts/templates/``."""
    out: dict[str, dict[str, Any]] = {}
    for env in ENVIRONMENTS:
        cap = env.capitalize()
        out[f"permission-boundary-{env}.json"] = _managed_policy_template(
            f"{cap}PermissionBoundary",
            boundary_name(env),
            f"Permission boundary for every {env} role created by a finplan pipeline: denies other environments' tagged or named resources, live-financial actions and boundary/budget tampering (design D5).",
            env_permission_boundary(env),
            env,
        )
        out[f"research-permission-boundary-{env}.json"] = _managed_policy_template(
            f"{cap}ResearchPermissionBoundary",
            research_boundary_name(env),
            f"Permission boundary for FinanceModel {env} research and job-execution roles: the {env} boundary plus denies on platform metadata, plan/publication/execution API writes and S3 writes outside research storage and the staging area (design D5, ENV-04).",
            research_permission_boundary(env),
            env,
        )
    out["permission-boundary-shared.json"] = _managed_policy_template(
        "SharedPermissionBoundary",
        boundary_name(SHARED),
        "Permission boundary for account-level tooling roles (pipelines, budget action execution): live-financial deny and boundary/budget protection.",
        shared_permission_boundary(),
        SHARED,
    )
    out["live-financial-deny.json"] = {
        "Description": "Live-financial deny statements included in every finplan permission boundary (ENV-05). Use these statements; do not grant any of these actions or secrets.",
        "Statement": live_financial_deny_statements(),
        "Metadata": {"finplan": {"generated_by": "finplan_contracts.boundaries"}},
    }
    return out


def all_templates() -> dict[str, dict[str, Any]]:
    """Every generated template (guardrails, budget, SSM access), keyed by file name."""
    from .budget import generate_templates as budget_templates
    from .iam import budget_state_writer_policy, to_cfn

    docs = dict(generate_templates())
    docs.update(budget_templates())
    docs["ssm-access-policy.json"] = _ssm_access_template()
    docs["budget-state-writer-policy.json"] = {
        "AWSTemplateFormatVersion": "2010-09-09",
        "Description": "Policy of the FinancialPlanning budget-state writer Lambda: the only runtime principal that writes under /finplan/shared/ (design D4).",
        "Resources": {
            "BudgetStateWriterPolicy": {
                "Type": "AWS::IAM::ManagedPolicy",
                "Properties": {"ManagedPolicyName": "finplan-shared-financialplanning-budget-state-writer", "PolicyDocument": to_cfn(budget_state_writer_policy())},
            }
        },
        "Metadata": {"finplan": {"generated_by": "finplan_contracts.iam", "cdk_wiring": "add-platform-foundation"}},
    }
    return docs


def _ssm_access_template() -> dict[str, Any]:
    from . import ssm as _ssm
    from .iam import SSM_READ_ACTIONS, SSM_WRITE_ACTIONS

    arn = "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter"
    own = [{"Fn::Sub": f"{arn}/finplan/${{Environment}}/${{Repo}}/*"}]
    return {
        "AWSTemplateFormatVersion": "2010-09-09",
        "Description": "SSM access for a repository's per-environment deploy role: PutParameter only on /finplan/<env>/<own-repo>/*, reads on /finplan/<same-env>/* and /finplan/shared/* (design D4, ENV-07). Generated equivalent: finplan_contracts.iam.ssm_access_policy.",
        "Parameters": {
            "Repo": {"Type": "String", "AllowedValues": list(_ssm.REPOS)},
            "Environment": {"Type": "String", "AllowedValues": list(_ssm.ENVIRONMENTS)},
        },
        "Resources": {
            "SsmAccessPolicy": {
                "Type": "AWS::IAM::ManagedPolicy",
                "Properties": {
                    "ManagedPolicyName": {"Fn::Sub": "finplan-${Environment}-${Repo}-ssm-access"},
                    "PolicyDocument": {
                        "Version": "2012-10-17",
                        "Statement": [
                            {"Sid": "WriteOwnRepoSegment", "Effect": "Allow", "Action": list(SSM_WRITE_ACTIONS), "Resource": own},
                            {
                                "Sid": "ReadSameEnvironmentAndShared",
                                "Effect": "Allow",
                                "Action": list(SSM_READ_ACTIONS),
                                "Resource": [
                                    {"Fn::Sub": f"{arn}/finplan/${{Environment}}"},
                                    {"Fn::Sub": f"{arn}/finplan/${{Environment}}/*"},
                                    {"Fn::Sub": f"{arn}/finplan/shared"},
                                    {"Fn::Sub": f"{arn}/finplan/shared/*"},
                                ],
                            },
                            {"Sid": "DenyWritesOutsideOwnSegment", "Effect": "Deny", "Action": list(SSM_WRITE_ACTIONS), "NotResource": own},
                        ],
                    },
                },
            }
        },
        "Metadata": {"finplan": {"generated_by": "finplan_contracts.boundaries", "cdk_wiring": "add-platform-foundation"}},
    }


def main(argv: list[str]) -> int:
    """``python -m finplan_contracts.boundaries [--check] [DIR]``: write or check the generated templates."""
    import argparse
    import sys

    ap = argparse.ArgumentParser(prog="finplan-contracts-templates")
    ap.add_argument("out_dir", nargs="?")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--template", help="check a synthesized template's role boundaries and shared resources")
    ap.add_argument("--env")
    args = ap.parse_args(argv)
    if args.template:
        tpl = json.loads(Path(args.template).read_text(encoding="utf-8"))
        findings = check_role_boundaries(tpl, args.env) + check_shared_resources(tpl)
        for f in findings:
            print(str(f), file=sys.stderr)
        print("PASS" if not findings else f"FAIL: {len(findings)} finding(s)")
        return 1 if findings else 0
    out_dir = Path(args.out_dir) if args.out_dir else contracts_root() / "templates"
    docs = all_templates()
    if args.check:
        rc = 0
        for name, doc in sorted(docs.items()):
            p = out_dir / name
            if not p.is_file() or json.loads(p.read_text(encoding="utf-8")) != doc:
                print(f"{p}: out of date", file=sys.stderr)
                rc = 1
        return rc
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, doc in sorted(docs.items()):
        (out_dir / name).write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")
        print(f"wrote {out_dir / name}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    import sys

    raise SystemExit(main(sys.argv[1:]))
