"""SSM parameter naming convention and write/read rules (design D4, D10, D11; ENV-07).

Names have the form ``/finplan/<environment>/<repo>/<category>/<name>``:

* ``<environment>`` is ``beta``, ``gamma`` or ``prod``, or the reserved segment
  ``shared`` for account-level, environment-independent values;
* ``<repo>`` is the lowercase repository name (the owning repository);
* ``<category>`` is one of :data:`CATEGORIES`;
* ``<name>`` is lowercase kebab-case.

Write rules enforced by :func:`check_write` (the IAM side is generated by
:mod:`finplan_contracts.iam`):

* only the owning repository writes under its ``<repo>`` segment (cross-repo
  writes are rejected);
* ``shared`` values are written only by the authenticated bootstrap or the
  contract-package publish step (FinancialPlanning), with exactly one runtime
  exception: the FinancialPlanning budget-state writer may write
  ``/finplan/shared/financialplanning/config/budget-state`` and nothing else;
* retired keys (D11: the per-repo ``config/budget-allocation`` keys and
  ``secret-ref/openai-api-key``) are rejected for new writes;
* a writer bound to an environment (a per-environment deploy role) writes only in
  that environment.

Reads (:func:`check_read`) cover the reader's own environment and ``shared``.

The module also registers the cross-repo keys of D1/D4/D10/D11/D12/D13/D16
(:data:`REGISTERED_KEYS`), validates parameter values for the keys whose value
shape is contractual (:func:`validate_value`), and exposes the cost-allocation tag
keys (:data:`COST_ALLOCATION_TAG_KEYS`, :func:`cost_allocation_tags`).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from typing import Any, Iterable

__all__ = [
    "BUDGET_ENFORCED_ROLE_NAMES",
    "ROOT",
    "ENVIRONMENTS",
    "SHARED",
    "REPOS",
    "CATEGORIES",
    "WRITER_KINDS",
    "COST_ALLOCATION_TAG_KEYS",
    "SsmName",
    "Writer",
    "Decision",
    "RegisteredKey",
    "REGISTERED_KEYS",
    "RETIRED_KEYS",
    "SsmNameError",
    "build",
    "parse",
    "validation_errors",
    "is_valid_name",
    "find_registered",
    "find_retired",
    "check_write",
    "check_read",
    "validate_value",
    "budget_enforced_role_name_keys",
    "cost_allocation_tags",
    "JEV_SECRET_NAME",
    "BUDGET_STATE_PARAMETER",
    "main",
]

ROOT = "finplan"
ENVIRONMENTS: tuple[str, ...] = ("beta", "gamma", "prod")
SHARED = "shared"
REPOS: tuple[str, ...] = ("financialplanning", "financemodel", "financelambdastool", "financeagent")
CATEGORIES: tuple[str, ...] = ("release", "contract", "api", "lambda", "job", "model", "agent", "config", "secret-ref")
NAME_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*\Z")

#: ``pipeline``: a repository's pipeline / deploy role; ``bootstrap``: the one-time
#: authenticated bootstrap; ``contract-publish``: the contract-package publish step
#: (FinancialPlanning only); ``runtime``: a deployed runtime principal.
WRITER_KINDS: tuple[str, ...] = ("pipeline", "bootstrap", "contract-publish", "runtime")
#: The only runtime principal allowed to write under ``shared`` (D4 runtime writer exception).
BUDGET_STATE_WRITER = "budget-state-writer"
BUDGET_STATE_PARAMETER = "/finplan/shared/financialplanning/config/budget-state"
JEV_SECRET_NAME = "finplan/shared/financemodel/jev-api-key"

#: Cost-allocation tag keys registered in the contract package (D10).
COST_ALLOCATION_TAG_KEYS: tuple[str, ...] = ("project", "owner-repo", "environment", "logical-role", "run-id")
PROJECT_TAG_VALUE = "finplan"


class SsmNameError(ValueError):
    """The parameter name violates the convention."""


@dataclass(frozen=True)
class SsmName:
    environment: str  # beta | gamma | prod | shared
    repo: str
    category: str
    name: str

    @property
    def path(self) -> str:
        return f"/{ROOT}/{self.environment}/{self.repo}/{self.category}/{self.name}"

    @property
    def is_shared(self) -> bool:
        return self.environment == SHARED

    def __str__(self) -> str:
        return self.path


# ------------------------------------------------------------------ build / parse
def validation_errors(path: Any) -> list[str]:
    """Reasons ``path`` violates the naming convention (empty when valid)."""
    if not isinstance(path, str):
        return ["parameter name must be a string"]
    if not path.startswith("/"):
        return ["parameter name must start with '/'"]
    parts = path.split("/")[1:]
    if len(parts) != 5:
        return [f"parameter name must have exactly 5 segments /{ROOT}/<environment>/<repo>/<category>/<name>, got {len(parts)}"]
    root, env, repo, category, name = parts
    errors = []
    if root != ROOT:
        errors.append(f"first segment must be '{ROOT}', got {root!r}")
    if env not in ENVIRONMENTS + (SHARED,):
        errors.append(f"environment segment must be one of {', '.join(ENVIRONMENTS + (SHARED,))}, got {env!r}")
    if repo not in REPOS:
        errors.append(f"repo segment must be one of {', '.join(REPOS)}, got {repo!r}")
    if category not in CATEGORIES:
        errors.append(f"category must be one of {', '.join(CATEGORIES)}, got {category!r}")
    if not NAME_RE.match(name):
        errors.append(f"name must be lowercase kebab-case, got {name!r}")
    return errors


def is_valid_name(path: Any) -> bool:
    return not validation_errors(path)


def parse(path: str) -> SsmName:
    """Parse and validate a parameter name; raises :class:`SsmNameError`."""
    errors = validation_errors(path)
    if errors:
        raise SsmNameError(f"{path!r}: " + "; ".join(errors))
    _, _, env, repo, category, name = path.split("/")
    return SsmName(env, repo, category, name)


def build(environment: str, repo: str, category: str, name: str) -> str:
    """Build a parameter name; raises :class:`SsmNameError` for any invalid segment."""
    path = f"/{ROOT}/{environment}/{repo}/{category}/{name}"
    parse(path)
    return path


# ------------------------------------------------------------------ registered keys
@dataclass(frozen=True)
class RegisteredKey:
    """A registered cross-repo key. ``environment`` is ``<env>`` (any of beta/gamma/prod) or ``shared``;
    ``repo`` is a repository or ``<repo>`` (each repository writes its own); ``name`` may contain
    one ``<...>`` placeholder (for example ``<tool>-arn``)."""

    key: str
    environment: str
    repo: str
    category: str
    name: str
    writers: tuple[str, ...]
    value: str  # value shape: text | json | json-manifest | budget-allocation | secret-name | role-names | release-id | number | parameter-ref | provider | model-id
    description: str
    decisions: tuple[str, ...] = ()

    def pattern(self) -> re.Pattern[str]:
        env = "(beta|gamma|prod)" if self.environment == "<env>" else re.escape(self.environment)
        repo = "(" + "|".join(REPOS) + ")" if self.repo == "<repo>" else re.escape(self.repo)
        name = re.sub(r"<[^>]+>", "[a-z0-9]+(?:-[a-z0-9]+)*", re.escape(self.name).replace(r"\<", "<").replace(r"\>", ">"))
        return re.compile(f"^/{ROOT}/{env}/{repo}/{re.escape(self.category)}/{name}\\Z")

    def matches(self, path: str) -> bool:
        return bool(self.pattern().match(path))

    def template(self) -> str:
        return f"/{ROOT}/{self.environment}/{self.repo}/{self.category}/{self.name}"


_P = ("pipeline",)
_B = ("bootstrap",)
_BP = ("bootstrap", "contract-publish")

REGISTERED_KEYS: tuple[RegisteredKey, ...] = (
    # release manifest and pointer, written by every deploy (D4)
    RegisteredKey("release-manifest", "<env>", "<repo>", "release", "manifest", _P, "json-manifest", "Release manifest (core/v1/release-manifest.json)", ("D4",)),
    RegisteredKey("current-release-id", "<env>", "<repo>", "release", "current-release-id", _P, "release-id", "Current release pointer", ("D4",)),
    # budget (D4, D10, D11)
    RegisteredKey("cost-ceiling-usd", SHARED, "financialplanning", "config", "cost-ceiling-usd", _B, "number", "Project cost ceiling in USD (initially 50)", ("D10",)),
    RegisteredKey("budget-allocation", SHARED, "financialplanning", "config", "budget-allocation", _B, "budget-allocation", "Category -> USD allocation map", ("D11",)),
    RegisteredKey("budget-state", SHARED, "financialplanning", "config", "budget-state", ("bootstrap", "runtime"), "json", "Budget state, written by the budget-state writer Lambda (only shared runtime writer)", ("D4",)),
    RegisteredKey("budget-enforced-role-names", "<env>", "<repo>", "config", "budget-enforced-role-names", _P, "role-names", "Role names the budget action denies at 100%", ("D4", "D11")),
    # account-level (environment-independent) tooling role names of each repository, for example its
    # pipeline and build roles; written by that repository's bootstrap (1.0.0, D16)
    RegisteredKey("shared-budget-enforced-role-names", SHARED, "<repo>", "config", "budget-enforced-role-names", _B, "role-names", "Account-level tooling role names the budget action denies at 100% (written by the repository's bootstrap)", ("D4", "D16")),
    # FinanceAgent explanation provider (D11, D12)
    RegisteredKey("explanation-provider", "<env>", "financeagent", "config", "explanation-provider", _P, "provider", "Explanation provider (default bedrock)", ("D11",)),
    RegisteredKey("explanation-model-id", "<env>", "financeagent", "config", "explanation-model-id", _P, "model-id", "Bedrock model or inference-profile ID", ("D11", "D12")),
    # Jev API key reference (D11)
    RegisteredKey("jev-api-key-secret-ref", SHARED, "financemodel", "secret-ref", "jev-api-key", _B, "secret-name", "Secret NAME of the TypeSafe Jev API key (never the value)", ("D11",)),
    # cross-repo references (D1, D4, D10)
    RegisteredKey("gateway-principal-ref", "<env>", "financeagent", "agent", "gateway-principal-ref", ("pipeline", "bootstrap"), "text", "Per-environment Gateway service role reference", ("D4", "D10")),
    # FinanceAgent identity provider: one Amazon Cognito user pool per environment (decision 15a, 2026-10-07)
    RegisteredKey("user-pool-ref", "<env>", "financeagent", "agent", "user-pool-ref", _P, "text", "Per-environment Cognito user pool reference (the OIDC identity provider)", ("D1", "D4", "D13")),
    RegisteredKey("authorizer-metadata-ref", "<env>", "financeagent", "agent", "authorizer-metadata-ref", _P, "text", "OIDC authorizer metadata (discovery URL) reference of the user pool", ("D1", "D4", "D13")),
    RegisteredKey("ci-test-client-secret-ref", "<env>", "financeagent", "secret-ref", "ci-test-client", _P, "secret-name", "CI test client secret NAME (never the value)", ("D1", "D4", "D13")),
    # FinanceLambdasTool direct-test principal: the project owner only, one per environment (decision 15b)
    RegisteredKey("direct-test-principal-name", "<env>", "financelambdastool", "config", "direct-test-principal-name", ("pipeline", "bootstrap"), "text", "Name of the single direct-test principal granted tool invoke (the project owner)", ("D4", "D13")),
    RegisteredKey("tool-catalog", "<env>", "financelambdastool", "contract", "tool-catalog", _P, "json", "Tool catalog (core/v1/tool-catalog.json)", ("D4", "D10")),
    RegisteredKey("tool-lambda-ref", "<env>", "financelambdastool", "lambda", "<tool>-arn", _P, "text", "Tool Lambda reference", ("D1",)),
    RegisteredKey("contract-registry-ref", SHARED, "financialplanning", "contract", "registry-ref", _BP, "text", "CodeArtifact registry reference", ("D1", "D3")),
    RegisteredKey("codeconnection-ref", SHARED, "<repo>", "config", "codeconnection-ref", _B, "text", "Reused CodeConnection reference, written by the bootstrap", ("D1", "D11")),
    RegisteredKey("plan-endpoint", "<env>", "financialplanning", "api", "plan-endpoint", _P, "text", "Plan lifecycle API endpoint", ("D1",)),
    RegisteredKey("ingestion-endpoint", "<env>", "financialplanning", "api", "ingestion-endpoint", _P, "text", "Ingestion API endpoint", ("D1",)),
    RegisteredKey("run-staging-ref", "<env>", "financialplanning", "config", "run-staging-ref", _P, "text", "Run-output staging reference", ("D1", "D10")),
    RegisteredKey("ingest-schedule", "<env>", "financialplanning", "config", "ingest-schedule", _P, "text", "Daily ingestion schedule time (OQ-6)", ("D1",)),
    RegisteredKey("job-endpoint", "<env>", "financemodel", "api", "job-endpoint", _P, "text", "Job submission interface endpoint", ("D1",)),
    # FinanceModel role references named in the platform's grants (snapshot reads, staging writes, staged-output reads)
    RegisteredKey("job-role-ref", "<env>", "financemodel", "job", "job-role-ref", _P, "text", "Per-environment job-execution role reference (read approved snapshots, write the run staging area)", ("D1", "D4", "D13")),
    RegisteredKey("job-api-role-ref", "<env>", "financemodel", "job", "job-api-role-ref", _P, "text", "Per-environment job API handler role reference (may read GET /v1/staged-outputs/*)", ("D1", "D4", "D13")),
    RegisteredKey("model-registry-ref", "<env>", "financemodel", "model", "registry-ref", _P, "text", "Model registry reference", ("D1",)),
)
# The tool role-class references (/lambda/role-<class>-arn) share the <tool>-arn shape and are covered by tool-lambda-ref.


@dataclass(frozen=True)
class RetiredKey:
    key: str
    pattern: re.Pattern[str]
    reason: str


RETIRED_KEYS: tuple[RetiredKey, ...] = (
    RetiredKey(
        "per-repo-budget-allocation",
        re.compile(r"^/finplan/(beta|gamma|prod|shared)/(financialplanning|financemodel|financelambdastool|financeagent)/config/budget-allocation\Z"),
        "RETIRED 2026-10-07 (D11): the budget is not split per repository; use /finplan/shared/financialplanning/config/budget-allocation",
    ),
    RetiredKey(
        "openai-api-key-secret-ref",
        re.compile(r"^/finplan/(beta|gamma|prod|shared)/(financialplanning|financemodel|financelambdastool|financeagent)/secret-ref/openai-api-key\Z"),
        "RETIRED 2026-10-07 (D11): no OpenAI secret is needed; the explanation provider is Amazon Bedrock with IAM auth",
    ),
)


def find_retired(path: str) -> RetiredKey | None:
    if path == "/finplan/shared/financialplanning/config/budget-allocation":
        return None  # the single registered allocation key replaces the retired per-repo keys
    return next((r for r in RETIRED_KEYS if r.pattern.match(path)), None)


def find_registered(path: str) -> RegisteredKey | None:
    if find_retired(path):
        return None
    return next((k for k in REGISTERED_KEYS if k.matches(path)), None)


#: Name of the per-repository budget-enforced role-name keys (D4, D16).
BUDGET_ENFORCED_ROLE_NAMES = "budget-enforced-role-names"


def budget_enforced_role_name_keys(repos: Iterable[str] = REPOS) -> list[str]:
    """Every key the budget action reads: per repository, the account-level (``shared``) list and the
    beta, gamma and prod lists (D4, D16)."""
    return [build(env, repo, "config", BUDGET_ENFORCED_ROLE_NAMES) for repo in repos for env in (SHARED, *ENVIRONMENTS)]


# ------------------------------------------------------------------ write / read rules
@dataclass(frozen=True)
class Writer:
    """Who is writing. ``environment`` binds a per-environment role to one environment."""

    repo: str
    kind: str = "pipeline"
    environment: str | None = None
    principal: str | None = None  # runtime principal name, e.g. "budget-state-writer"


@dataclass
class Decision:
    allowed: bool
    path: str
    reasons: list[str] = field(default_factory=list)

    def __bool__(self) -> bool:
        return self.allowed


def check_write(path: str, writer: Writer) -> Decision:
    """Whether ``writer`` may write (PutParameter) ``path`` (new write)."""
    reasons = validation_errors(path)
    if reasons:
        return Decision(False, path, reasons)
    if writer.repo not in REPOS:
        return Decision(False, path, [f"unknown writer repository {writer.repo!r}"])
    if writer.kind not in WRITER_KINDS:
        return Decision(False, path, [f"unknown writer kind {writer.kind!r}"])
    p = parse(path)
    if p.repo != writer.repo:
        reasons.append(f"cross-repo write: {writer.repo} may write only under its own segment /{ROOT}/<env>/{writer.repo}/, not /{ROOT}/{p.environment}/{p.repo}/")
    retired = find_retired(path)
    if retired:
        reasons.append(f"retired key, new writes are rejected: {retired.reason}")
    if writer.kind == "runtime":
        if not (path == BUDGET_STATE_PARAMETER and writer.repo == "financialplanning" and writer.principal == BUDGET_STATE_WRITER):
            reasons.append(
                f"runtime principals do not write SSM parameters; the only runtime writer is the financialplanning "
                f"{BUDGET_STATE_WRITER}, and only {BUDGET_STATE_PARAMETER}"
            )
    elif p.is_shared:
        if writer.kind == "pipeline":
            reasons.append("shared values are written only by the bootstrap or the contract-publish step, not by a deploy pipeline")
        if writer.kind == "contract-publish" and writer.repo != "financialplanning":
            reasons.append("the contract-publish step belongs to financialplanning")
    else:
        if writer.kind == "contract-publish":
            reasons.append("the contract-publish step writes only shared contract references")
    if writer.environment is not None and writer.environment != p.environment:
        reasons.append(f"writer is bound to environment {writer.environment!r} and cannot write {p.environment!r} parameters")
    reg = find_registered(path)
    if reg is not None and writer.kind not in reg.writers and not reasons:
        reasons.append(f"registered key {reg.key} is written only by: {', '.join(reg.writers)}")
    return Decision(not reasons, path, reasons)


def check_read(path: str, reader_environment: str) -> Decision:
    """Reads cover the reader's own environment and ``shared`` (D4)."""
    reasons = validation_errors(path)
    if reasons:
        return Decision(False, path, reasons)
    if reader_environment not in ENVIRONMENTS + (SHARED,):
        return Decision(False, path, [f"unknown reader environment {reader_environment!r}"])
    p = parse(path)
    if p.environment not in (reader_environment, SHARED):
        reasons.append(f"cross-environment read: a {reader_environment} principal reads only /{ROOT}/{reader_environment}/* and /{ROOT}/{SHARED}/*")
    return Decision(not reasons, path, reasons)


# ------------------------------------------------------------------ values
_SECRET_NAME_RE = re.compile(r"^[A-Za-z0-9/_+=.@-]{1,512}\Z")
_ROLE_NAME_RE = re.compile(r"^[\w+=,.@-]{1,64}\Z")
_RELEASE_ID_RE = re.compile(r"^rel_[0-9A-HJKMNP-TV-Z]{26}\Z")
_PROVIDER_RE = re.compile(r"^[a-z][a-z0-9_-]{0,63}\Z")
_MODEL_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}\Z")
# A secret-ref holds a NAME. Values that look like ARNs or like credential material are rejected.
_CREDENTIAL_LIKE = re.compile(r"(?i)^(arn:|sk-|AKIA|ASIA|ghp_|xox[abp]-|eyJ)|-----BEGIN")


def _parse_role_names(value: str) -> list[str]:
    value = value.strip()
    if value.startswith("["):
        data = json.loads(value)
        if not isinstance(data, list) or not all(isinstance(x, str) for x in data):
            raise ValueError("role names JSON must be an array of strings")
        return data
    return [x.strip() for x in value.split(",")]


def validate_value(path: str, value: str, *, cost_ceiling_usd: float | None = None) -> list[str]:
    """Validate a parameter value for registered keys with a contractual value shape.

    Returns a list of problems (empty when the value is acceptable). Unregistered
    keys are only checked for the name convention.
    """
    problems = validation_errors(path)
    if problems:
        return problems
    if not isinstance(value, str):
        return ["SSM parameter values are strings"]
    retired = find_retired(path)
    if retired:
        return [f"retired key: {retired.reason}"]
    p = parse(path)
    reg = find_registered(path)
    if p.category == "secret-ref" or (reg and reg.value == "secret-name"):
        if not _SECRET_NAME_RE.match(value) or _CREDENTIAL_LIKE.search(value):
            problems.append("secret-ref parameters hold only a Secrets Manager secret name, never an ARN or a secret value")
        if reg and reg.key == "jev-api-key-secret-ref" and value != JEV_SECRET_NAME:
            problems.append(f"the Jev secret-ref holds the secret name {JEV_SECRET_NAME!r}")
        return problems
    if reg is None:
        return problems
    try:
        if reg.value == "json-manifest":
            from .validate import validate

            res = validate(json.loads(value), "release-manifest")
            problems += [i.message for i in res.issues]
            doc = json.loads(value)
            if isinstance(doc, dict) and (doc.get("repo"), doc.get("environment")) != (p.repo, p.environment):
                problems.append("manifest repo/environment do not match the parameter path")
        elif reg.value == "budget-allocation":
            from .validate import validate

            ctx = {"cost_ceiling_usd": cost_ceiling_usd} if cost_ceiling_usd is not None else None
            res = validate(json.loads(value), "budget-allocation", context=ctx)
            problems += [i.message for i in res.issues]
        elif reg.value == "json":
            json.loads(value)
        elif reg.value == "number":
            n = float(value)
            if not n > 0:
                problems.append("value must be a positive number")
        elif reg.value == "release-id":
            if not _RELEASE_ID_RE.match(value):
                problems.append("value must be a release_id (rel_ + ULID)")
        elif reg.value == "role-names":
            names = _parse_role_names(value)
            if not names:
                problems.append("at least one role name is required")
            for n in names:
                if not _ROLE_NAME_RE.match(n):
                    problems.append(f"{n!r} is not an IAM role name (role names only, never ARNs)")
        elif reg.value == "provider":
            if not _PROVIDER_RE.match(value):
                problems.append("provider must be a lowercase provider key such as 'bedrock'")
        elif reg.value == "model-id":
            if not _MODEL_ID_RE.match(value) or value.startswith("arn:"):
                problems.append("model ID must be a Bedrock model or inference-profile ID, not an ARN")
    except (ValueError, json.JSONDecodeError) as exc:
        problems.append(f"invalid value: {exc}")
    return problems


# ------------------------------------------------------------------ tags
def cost_allocation_tags(repo: str, environment: str, logical_role: str, run_id: str | None = None) -> dict[str, str]:
    """The registered cost-allocation tags for a resource (D10)."""
    if repo not in REPOS:
        raise ValueError(f"unknown repo {repo!r}")
    if environment not in ENVIRONMENTS + (SHARED,):
        raise ValueError(f"unknown environment {environment!r}")
    if not re.match(r"^[a-z][a-z0-9-]{0,62}\Z", logical_role):
        raise ValueError(f"logical-role must be lowercase kebab-case, got {logical_role!r}")
    tags = {"project": PROJECT_TAG_VALUE, "owner-repo": repo, "environment": environment, "logical-role": logical_role}
    if run_id is not None:
        if not re.match(r"^run_[0-9A-HJKMNP-TV-Z]{26}\Z", run_id):
            raise ValueError("run-id must be a run_id")
        tags["run-id"] = run_id
    return tags


# ------------------------------------------------------------------ CLI
def _print_decision(d: Decision) -> int:
    if d.allowed:
        print(f"OK {d.path}")
        return 0
    for r in d.reasons:
        print(f"DENY {d.path}: {r}", file=sys.stderr)
    return 1


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(prog="finplan-conformance ssm-path", description="Build or check SSM parameter names (/finplan/<env|shared>/<repo>/<category>/<name>).")
    sub = ap.add_subparsers(dest="cmd", required=True)
    b = sub.add_parser("build", help="build a parameter name")
    b.add_argument("--env", required=True)
    b.add_argument("--repo", required=True)
    b.add_argument("--category", required=True)
    b.add_argument("--name", required=True)
    c = sub.add_parser("check", help="check parameter names (and optionally a write or read)")
    c.add_argument("paths", nargs="+")
    c.add_argument("--writer-repo")
    c.add_argument("--writer-kind", default="pipeline", choices=WRITER_KINDS)
    c.add_argument("--writer-env")
    c.add_argument("--writer-principal")
    c.add_argument("--reader-env")
    v = sub.add_parser("value", help="validate a parameter value")
    v.add_argument("path")
    v.add_argument("value")
    v.add_argument("--ceiling", type=float)
    sub.add_parser("keys", help="list registered and retired keys")
    args = ap.parse_args(argv)

    if args.cmd == "build":
        try:
            print(build(args.env, args.repo, args.category, args.name))
            return 0
        except SsmNameError as exc:
            print(str(exc), file=sys.stderr)
            return 1
    if args.cmd == "check":
        rc = 0
        for path in args.paths:
            if args.writer_repo:
                rc |= _print_decision(check_write(path, Writer(args.writer_repo, args.writer_kind, args.writer_env, args.writer_principal)))
            elif args.reader_env:
                rc |= _print_decision(check_read(path, args.reader_env))
            else:
                errs = validation_errors(path)
                rc |= _print_decision(Decision(not errs, path, errs))
        return rc
    if args.cmd == "value":
        problems = validate_value(args.path, args.value, cost_ceiling_usd=args.ceiling)
        for pr in problems:
            print(f"INVALID {args.path}: {pr}", file=sys.stderr)
        if not problems:
            print(f"OK {args.path}")
        return 1 if problems else 0
    for k in REGISTERED_KEYS:
        print(f"{k.template():70s} writers={','.join(k.writers):28s} value={k.value}")
    for r in RETIRED_KEYS:
        print(f"RETIRED {r.key}: {r.reason}")
    return 0


def iter_registered(paths: Iterable[str]) -> list[tuple[str, RegisteredKey | None]]:
    return [(p, find_registered(p)) for p in paths]
